// Stable IDs are shared by routing, progress, assessments, and the roadmap.
export const stages = [
  {
    title: "Foundations",
    description: "Turn small components into an interactive interface.",
    level: "Beginner",
  },
  {
    title: "State design",
    description: "Choose where state lives and how it changes.",
    level: "Developing",
  },
  {
    title: "Effects & reuse",
    description: "Connect to the outside world without surprises.",
    level: "Developing",
  },
  {
    title: "Application architecture",
    description: "Coordinate state and build a multi-page app.",
    level: "Intermediate",
  },
  {
    title: "Performance & reliability",
    description: "Measure, prioritize, and recover gracefully.",
    level: "Intermediate",
  },
];
const question = (prompt, options, answer, explanation) => ({
  prompt,
  options,
  answer,
  explanation,
});
const lesson = (
  id,
  title,
  stage,
  summary,
  understand,
  action,
  code,
  practice,
  check,
  reflection,
) => ({
  id,
  title,
  stage,
  summary,
  understand,
  action,
  code,
  practice,
  check,
  reflection,
  assessmentIds: [`${id}:practice`, `${id}:check`],
  objectives: [summary, action],
  hints: [practice.explanation.split(". ")[0] + ".", practice.explanation],
  docs: "https://18.react.dev/learn",
});
const entries = [
  lesson(
    "components",
    "Components & JSX",
    0,
    "Describe an interface with reusable components.",
    "A component is a capitalized JavaScript function that returns JSX. JSX describes the interface; React uses it to update the DOM. Braces insert JavaScript expressions, while className supplies a CSS class. Composition puts small components together.",
    "Change the learner name and inspect the component tree.",
    `function Greeting({ name }) {\n  return <h3>Hello, {name || 'learner'}!</h3>;\n}\n// In the parent:\n<Greeting name={name} />`,
    question(
      "Which JSX passes a JavaScript variable to Greeting?",
      [
        '<Greeting name="name" />',
        "<Greeting name={name} />",
        "<greeting name={name} />",
      ],
      1,
      "Braces evaluate the variable. Quotes pass literal text, and a lowercase tag is treated as a built-in element.",
    ),
    question(
      "What should a component do during rendering?",
      [
        "Describe UI from its inputs",
        "Change the DOM directly",
        "Save data to a server",
      ],
      0,
      "Rendering should be pure: describe UI from props and state. External synchronization belongs elsewhere.",
    ),
    "Which smaller components could you extract from a task card?",
  ),
  lesson(
    "props",
    "Props & composition",
    0,
    "Pass data down and compose content with children.",
    "Props are read-only inputs from a parent. A child requests changes by calling a callback supplied by its parent. The children prop lets a wrapper accept content without knowing its details.",
    "Rename the learner, then send a thank-you from the child.",
    `function Profile({ name, onThank, children }) {\n  return <article>\n    <h3>{name}</h3>{children}\n    <button onClick={onThank}>Send thanks</button>\n  </article>;\n}`,
    question(
      "How should a child request a change in its parent?",
      ["Mutate its props", "Call a callback prop", "Find the parent DOM node"],
      1,
      "Call a callback prop. The parent owns the state and decides how to update it.",
    ),
    question(
      "What does children represent?",
      [
        "Only an array of components",
        "Content nested inside a component tag",
        "A copy of parent state",
      ],
      1,
      "Content nested inside a component tag is passed as children; it can include text, elements, or other renderable values.",
    ),
    "When would composition be more useful than adding another boolean prop?",
  ),
  lesson(
    "state",
    "Events & state",
    0,
    "Make the interface respond to user actions.",
    "useState remembers data between renders. Its setter requests another render; changing an ordinary local variable does not. Event handlers are functions passed to elements, not functions invoked while rendering.",
    "Increment the counter twice and reset it.",
    `const [count, setCount] = useState(0);\n<button onClick={() => setCount(c => c + 1)}>Increment</button>\n<button onClick={() => setCount(0)}>Reset count</button>`,
    question(
      "Which handler runs when the button is clicked?",
      [
        "onClick={setCount(count + 1)}",
        "onClick={() => setCount(c => c + 1)}",
        "onClick={count + 1}",
      ],
      1,
      "Pass a function to onClick. Calling the setter during rendering causes another render immediately.",
    ),
    question(
      "Why does changing let count alone not update the screen?",
      [
        "React only supports constants",
        "Local variables are automatically saved",
        "React needs a state update to request rendering",
      ],
      2,
      "React needs a state update to request rendering. A local variable is recreated each time the component runs.",
    ),
    "Which values in a form need state and which can be calculated?",
  ),
  lesson(
    "lists",
    "Conditions, lists & keys",
    0,
    "Render collections with stable identity.",
    "Use conditions to include or exclude UI and map to render collections. A stable key tells React which item is which across insertions and reordering. Index keys can associate state with the wrong item when a list changes.",
    "Add a task and reverse the list; track its stable ID.",
    `setTasks(items => [...items, { id: nextId, title: 'New task' }]);\n{tasks.map(task => <li key={task.id}>{task.title}</li>)}\n// Reverse a copy, never mutate state:\nsetTasks(items => [...items].reverse());`,
    question(
      "Choose a key for tasks that can be reordered.",
      [
        "The array index",
        "Math.random() during render",
        "A persistent task.id",
      ],
      2,
      "A persistent task.id follows the same task through reordering. Indexes track positions and random keys recreate items.",
    ),
    question(
      "What should an empty task collection display?",
      ["An explicit empty state", "A broken list item", "A fake task"],
      0,
      "An explicit empty state explains what happened and how to add the first item.",
    ),
    "What would happen to an editable row if its key changed on every render?",
  ),
  lesson(
    "snapshots",
    "State snapshots & batching",
    1,
    "Explain queued updates using the current render’s snapshot.",
    "Each render receives a snapshot of state. A setter does not change that snapshot inside the running handler. React batches updates; functional updaters receive the queued value, so multiple increments can compose correctly.",
    "Compare three snapshot updates with three functional updates.",
    `// One event, one captured count:\nsetCount(count + 1);\nsetCount(count + 1);\nsetCount(count + 1); // net +1\n// Updaters compose:\nsetCount(c => c + 1);\nsetCount(c => c + 1);\nsetCount(c => c + 1); // net +3`,
    question(
      "Starting at 0, what do three setCount(count + 1) calls in one handler produce?",
      ["1", "3", "0"],
      0,
      "All three calls capture the same count and queue the same replacement value, 1.",
    ),
    question(
      "When is a functional updater especially useful?",
      [
        "When the next value depends on the previous value",
        "Only with strings",
        "To mutate the previous value",
      ],
      0,
      "When the next value depends on the previous value, an updater composes with other queued updates.",
    ),
    "Why might a delayed callback still see an older value?",
  ),
  lesson(
    "immutable",
    "Immutable & derived state",
    1,
    "Update collections without duplicating derived values.",
    "Treat state objects and arrays as read-only. Copy the parts you change with map, filter, or spread. Calculate filtered lists and totals during rendering rather than synchronizing redundant state with an Effect.",
    "Complete a task and filter the list to unfinished tasks.",
    `setTasks(items => items.map(task =>\n  task.id === id ? { ...task, done: !task.done } : task\n));\nconst visible = onlyOpen ? tasks.filter(t => !t.done) : tasks;\nconst remaining = tasks.filter(t => !t.done).length;`,
    question(
      "How should you calculate the remaining task count?",
      [
        "Store it separately and synchronize in an Effect",
        "Calculate it from tasks during rendering",
        "Mutate a global counter",
      ],
      1,
      "Calculate it from tasks during rendering. This prevents task state and a duplicated count from drifting apart.",
    ),
    question(
      "Which update preserves immutability?",
      [
        "tasks[0].done = true",
        "tasks.push(newTask)",
        "tasks.map(t => t.id === id ? { ...t, done: true } : t)",
      ],
      2,
      "map creates a new array, and the changed task receives a new object. Unchanged tasks retain their references.",
    ),
    "Which values in the Study Planner should never be stored separately?",
  ),
  lesson(
    "forms",
    "Controlled forms & validation",
    1,
    "Keep input, validation, and submission in sync.",
    "A controlled input receives value from state and updates it with onChange. Prevent default form navigation, validate before saving, and connect errors to their fields. A visible label is more useful than a placeholder alone.",
    "Submit an empty title, then save a valid task.",
    `function submit(event) {\n  event.preventDefault();\n  if (!title.trim()) { setError('Enter a task title.'); return; }\n  setSaved(title.trim());\n  setError('');\n}\n<input value={title} onChange={e => setTitle(e.target.value)} />`,
    question(
      "Where should invalid input be handled?",
      [
        "Before saving, with a connected field error",
        "After silently saving it",
        "Only in a placeholder",
      ],
      0,
      "Validate before saving and show an error connected to the field so learners can correct the input.",
    ),
    question(
      "What makes an input controlled?",
      [
        "A ref alone",
        "value from state and an onChange handler",
        "An initial placeholder",
      ],
      1,
      "value from state and an onChange handler keep React state as the source of truth.",
    ),
    "How can you help someone recover from a validation error?",
  ),
  lesson(
    "identity",
    "Shared state & identity",
    1,
    "Lift shared state and intentionally reset local state.",
    "Move shared state to the closest common parent. Pass values down and callbacks up. React associates state with component type, position, and keys; changing a key can intentionally reset a subtree.",
    "Change the shared name, edit the draft, and switch learner to reset the draft.",
    `const [name, setName] = useState('Ada');\n<input value={name} onChange={e => setName(e.target.value)} />\n<Preview name={name} />\n<Draft key={learnerId} /> // new identity resets local state`,
    question(
      "Two sibling components need the same selected task. Where should it live?",
      [
        "In both siblings independently",
        "In their closest common parent",
        "In a DOM attribute",
      ],
      1,
      "Their closest common parent can own the shared selection and pass it to both children.",
    ),
    question(
      "What happens when a component gets a different key?",
      [
        "Its old local state is preserved forever",
        "React creates a new identity and resets local state",
        "Only its CSS changes",
      ],
      1,
      "A different key creates a new component identity, so React resets that component’s local state.",
    ),
    "When is resetting a draft desirable, and when would it lose useful work?",
  ),
  lesson(
    "refs",
    "Refs & focus",
    2,
    "Use refs for DOM access and values outside rendering.",
    "A ref is a stable container whose current value can change without triggering a render. Use state for displayed data and refs for DOM nodes or timer IDs. Focus an input from an event handler, and avoid reading or writing DOM during rendering.",
    "Use the focus button to move focus into the task input.",
    `const inputRef = useRef(null);\n<button onClick={() => inputRef.current?.focus()}>Focus task input</button>\n<input ref={inputRef} aria-label="Task to focus" />`,
    question(
      "Where should a displayed counter value live?",
      ["In state", "Only in ref.current", "In a module variable"],
      0,
      "Displayed data belongs in state so changes trigger rendering. Changing ref.current alone does not.",
    ),
    question(
      "When is inputRef.current available for focus?",
      [
        "Before the input has mounted",
        "After React attaches the DOM node",
        "Only on the server",
      ],
      1,
      "React attaches the DOM node before event handlers run, so an event handler can focus the mounted input.",
    ),
    "Why is a timer ID a good candidate for a ref?",
  ),
  lesson(
    "effects",
    "Effects & cleanup",
    2,
    "Synchronize an external subscription and clean it up.",
    "Effects synchronize with systems outside React. Dependencies describe the reactive values used by setup. Before setup runs again with changed dependencies, cleanup removes the previous subscription; cleanup also runs on unmount. Strict Mode performs an extra development setup/cleanup check.",
    "Mount the subscription, change rooms, and unmount it. Inspect the lifecycle log.",
    `useEffect(() => {\n  const receive = event => setMessage(event.detail);\n  window.addEventListener('room:' + room, receive);\n  return () => window.removeEventListener('room:' + room, receive);\n}, [room]);`,
    question(
      "A subscription uses room. What belongs in the dependency array?",
      ["Nothing, even when room changes", "room", "A random number"],
      1,
      "room is a reactive value used by setup. Including it replaces the old subscription when the room changes.",
    ),
    question(
      "When does cleanup run?",
      [
        "Only when the browser closes",
        "Before changed-dependency setup and on unmount",
        "Before every event handler",
      ],
      1,
      "Cleanup runs before the next setup when dependencies change and when the component unmounts. Strict Mode also checks setup/cleanup in development.",
    ),
    "Why is a value calculated from props usually not an Effect?",
  ),
  lesson(
    "fetching",
    "Fetching & request races",
    2,
    "Handle loading, empty, failure, retry, and stale results.",
    "Requests can finish in a different order than they start. Abort obsolete work and ignore stale results. Model explicit request states so loading, failure, and an empty successful response remain distinguishable. This lab uses a local asynchronous service with deterministic scenarios.",
    "Load resources, try an empty result, then simulate a failure and retry.",
    `useEffect(() => {\n  const controller = new AbortController();\n  let active = true;\n  loadResources(topic, scenario, controller.signal).then(items => {\n    if (active) setResult({ status: 'success', items });\n  }).catch(error => {\n    if (active && error.name !== 'AbortError')\n      setResult({ status: 'error', items: [] });\n  });\n  return () => { active = false; controller.abort(); };\n}, [topic, scenario, attempt]);`,
    question(
      "The old request finishes after the new request. What should happen?",
      [
        "The old response replaces the new results",
        "Ignore the obsolete response",
        "Combine results without checking",
      ],
      1,
      "Ignore the obsolete response. Cancellation and an active-request guard prevent stale data from overwriting the current selection.",
    ),
    question(
      "Is an empty response the same as a request failure?",
      [
        "Yes",
        "No; it is a successful response with no items",
        "Only if loading lasted a second",
      ],
      1,
      "An empty response is successful but contains no items. It needs a different message from a failed request.",
    ),
    "Which request states would a real search page need?",
  ),
  lesson(
    "custom-hooks",
    "Custom hooks",
    2,
    "Reuse stateful logic without sharing state accidentally.",
    "Custom hooks are functions whose names start with use and that can call other hooks. They share logic, not a single state instance. Keep hooks unconditional at the top level. A persistence hook can synchronize local state with browser storage and report storage failures.",
    "Edit both independent drafts and reload to verify persistence.",
    `function useDraft(key) {\n  const [value, setValue] = useState(() => readDraft(key));\n  useEffect(() => {\n    try { localStorage.setItem(key, JSON.stringify(value)); }\n    catch { /* report storage unavailable */ }\n  }, [key, value]);\n  return [value, setValue];\n}\nconst [first, setFirst] = useDraft('react-workspace:draft-a');`,
    question(
      "Two components call the same custom hook. What do they share?",
      [
        "Automatically the same state",
        "The logic; state is separate for each call",
        "The same DOM node",
      ],
      1,
      "Custom hooks share logic. Each call has independent state unless the hook explicitly connects to shared context or an external store.",
    ),
    question(
      "Where may a hook be called?",
      [
        "Inside a conditional event handler",
        "At the top level of a component or custom hook",
        "Inside any loop",
      ],
      1,
      "Call hooks at the top level of a component or custom hook so their order remains stable.",
    ),
    "Which repeated logic in your project deserves a custom hook?",
  ),
  lesson(
    "reducers",
    "Reducers & action history",
    3,
    "Describe state changes with explicit actions.",
    "A reducer is a pure function from current state and action to next state. Events dispatch actions describing what happened. Reducers centralize related transitions and are easy to test without rendering a component. IDs, storage writes, and other side effects belong outside the reducer.",
    "Dispatch add, complete, and reset actions; inspect their state differences.",
    `function taskReducer(state, action) {\n  switch (action.type) {\n    case 'add': return [...state, action.task];\n    case 'toggle': return state.map(t =>\n      t.id === action.id ? { ...t, done: !t.done } : t);\n    case 'reset': return [];\n    default: return state;\n  }\n}`,
    question(
      "Which operation belongs outside a reducer?",
      [
        "Returning a new array",
        "Writing to localStorage",
        "Switching on action.type",
      ],
      1,
      "Writing to localStorage is a side effect. Reducers should compute the next state without changing the outside world.",
    ),
    question(
      "What does dispatch receive?",
      [
        "An action describing what happened",
        "A DOM node",
        "The useReducer function",
      ],
      0,
      "dispatch receives an action; React passes it with the current state to the reducer.",
    ),
    "Which actions would describe editing and deleting tasks?",
  ),
  lesson(
    "context",
    "Context + reducer",
    3,
    "Share state with distant consumers through a provider.",
    "Context makes a value available to descendants without passing it through every intermediate component. A reducer manages transitions while context distributes state and dispatch. Consumers read the closest provider. Keep local state local, and avoid placing every value into one global context.",
    "Change the shared topic in one consumer and observe the other consumer.",
    `const TopicContext = createContext(null);\nfunction TopicProvider({ children }) {\n  const [topic, dispatch] = useReducer(topicReducer, 'JSX');\n  return <TopicContext.Provider value={{ topic, dispatch }}>\n    {children}\n  </TopicContext.Provider>;\n}\nconst { topic, dispatch } = useContext(TopicContext);`,
    question(
      "Which provider does useContext read?",
      [
        "The closest matching provider above the consumer",
        "Any provider in any branch",
        "Only the first provider in the file",
      ],
      0,
      "A consumer reads the closest matching provider above it in the rendered component tree.",
    ),
    question(
      "Does Context replace all local state?",
      [
        "Yes, every field belongs in Context",
        "No; keep state close to where it is used",
        "Only when using a reducer",
      ],
      1,
      "Keep state close to where it is used. Context helps with shared access, not every local input.",
    ),
    "Which Study Planner values need Context, and which belong in a form?",
  ),
  lesson(
    "routing",
    "Routes & URL state",
    3,
    "Connect URLs to nested screens and shareable filters.",
    "A router matches the URL to components. Nested routes render through an Outlet, dynamic segments become parameters, and search parameters encode shareable filters. Use Link for internal navigation. BrowserRouter needs the hosting server to serve the app shell for direct route requests.",
    "Open task details and change the URL filter in the route explorer.",
    `<Routes>\n  <Route path="/tasks" element={<TaskLayout />}>\n    <Route index element={<TaskList />} />\n    <Route path=":taskId" element={<TaskDetail />} />\n  </Route>\n</Routes>\n// TaskLayout renders <Outlet />\nconst { taskId } = useParams();\nconst [search, setSearch] = useSearchParams();`,
    question(
      "Where should a shareable task filter live?",
      [
        "Only in a local variable",
        "In URL search parameters",
        "In a random key",
      ],
      1,
      "URL search parameters let a filter survive navigation and be shared in a link.",
    ),
    question(
      "What renders the matched child route?",
      ["Outlet", "useState", "A second BrowserRouter"],
      0,
      "Outlet renders the matched child route inside its parent layout. Do not nest BrowserRouter instances.",
    ),
    "Which UI choices deserve a URL and which are temporary?",
  ),
  lesson(
    "memoization",
    "Measure before memoizing",
    4,
    "Compare memoized and ordinary component updates.",
    "memo can skip a child render when its props compare equal. useMemo caches a calculation and useCallback caches a function identity between dependency changes. These are performance tools, not correctness guarantees. Measure a real bottleneck before adding them; development timings are noisy.",
    "Update unrelated state with memoization off and on, then change a real prop.",
    `const StableCard = memo(Card);\nconst onSelect = useCallback(() => setSelected(s => !s), []);\nconst summary = useMemo(() => topics.join(' · '), [topics]);\n<Profiler id="card" onRender={recordCommit}>\n  <StableCard title={title} onSelect={onSelect} />\n</Profiler>`,
    question(
      "A memoized child gets a new inline function every render. What can happen?",
      [
        "Its props compare unequal and it renders again",
        "It can never render",
        "Its state disappears",
      ],
      0,
      "A new function reference compares unequal. A stable callback may help a memoized child, but only optimize when measurement supports it.",
    ),
    question(
      "When should memoization be required for correctness?",
      ["Always", "Never; it is an optimization", "Only in Context"],
      1,
      "Memoization is an optimization. Your code should remain correct if React recalculates or renders again.",
    ),
    "What evidence would justify keeping an optimization?",
  ),
  lesson(
    "transitions",
    "Transitions & deferred values",
    4,
    "Keep urgent input separate from slower result rendering.",
    "In React 18, startTransition marks state updates scheduled synchronously inside its callback as non-urgent. Keep controlled text input updates urgent. useDeferredValue lets a consumer temporarily use an older value. Neither feature makes a network request faster or moves work to a worker.",
    "Type a search and compare transition and deferred-value modes.",
    `setText(nextText); // urgent controlled input\nstartTransition(() => setQuery(nextText)); // React 18: synchronous\n// Alternative consumer strategy:\nconst deferredText = useDeferredValue(text);\nconst visibleQuery = mode === 'deferred' ? deferredText : query;`,
    question(
      "Which update should remain urgent?",
      [
        "The controlled text input",
        "The expensive results panel",
        "Every update must be non-urgent",
      ],
      0,
      "The controlled text input should remain urgent so typing stays responsive while results catch up.",
    ),
    question(
      "Does React 18 track a setState after await in the same transition callback?",
      [
        "Yes, automatically",
        "No; transition updates must be scheduled synchronously",
        "Only with useMemo",
      ],
      1,
      "React 18 marks updates scheduled synchronously in the transition callback. A later update after await is outside that scope.",
    ),
    "How is a pending render different from a loading request?",
  ),
  lesson(
    "reliability",
    "Loading, recovery & testing",
    4,
    "Load code on demand and recover from render failures.",
    "React.lazy loads a component when needed. Suspense displays a fallback while supported work, such as lazy component loading, is pending; it does not automatically detect ordinary Effect-based fetching. Error boundaries catch descendant render errors, not arbitrary event-handler or asynchronous errors. Tests should exercise behavior users observe.",
    "Load the lazy panel, trigger a render error, and recover with the boundary.",
    `const LazyPanel = lazy(() => import('./LazyPanel'));\n<ErrorBoundary>\n  <Suspense fallback={<p>Loading panel…</p>}>\n    <LazyPanel />\n  </Suspense>\n</ErrorBoundary>`,
    question(
      "Which test best verifies task creation?",
      [
        "Assert an internal setter was called",
        "Enter a title, submit, and find the new task",
        "Check a CSS class only",
      ],
      1,
      "Enter a title, submit, and find the new task. This verifies behavior through the same interface a user operates.",
    ),
    question(
      "Does Suspense automatically handle fetch in useEffect?",
      [
        "Yes, every fetch suspends",
        "No; ordinary Effect fetching needs explicit request state",
        "Only with an empty dependency array",
      ],
      1,
      "Ordinary Effect fetching needs explicit request state. Suspense responds to supported suspending sources such as lazy components.",
    ),
    "What would you show if one panel failed while the rest of the page still worked?",
  ),
];
export const lessons = entries.map((entry, order) => ({
  ...entry,
  order,
  level: stages[entry.stage].level,
  prerequisites: order ? [entries[order - 1].id] : [],
  prediction: {
    ...entry.practice,
    prompt: `Predict before exploring: ${entry.practice.prompt}`,
  },
}));
export const lessonById = Object.assign(
  Object.create(null),
  Object.fromEntries(lessons.map((entry) => [entry.id, entry])),
);
export const legacyRoutes = {
  "/useState": "state",
  "/useEffect": "effects",
  "/useContext": "context",
  "/useReducer": "reducers",
  "/useCallback": "memoization",
  "/useTransition": "transitions",
  "/reactRouting": "routing",
  "/hooks": "state",
  "/jsx": "components",
};

const predictions = [
  question(
    "If you change the name input to Grace, which heading appears?",
    ["Hello, Grace!", "Hello, Ada!", "The component disappears"],
    0,
    "The parent passes its latest name to Greeting, which renders the new prop.",
  ),
  question(
    "When the child sends thanks, where is the count updated?",
    [
      "The parent that owns thanks",
      "Inside the name prop",
      "In the document title",
    ],
    0,
    "The child calls onThank. The callback updates the state owned by its parent.",
  ),
  question(
    "After two increments and a reset, what is the count?",
    ["2", "0", "3"],
    1,
    "Each increment adds one. Reset queues a replacement value of zero.",
  ),
  question(
    "After reversing the task list, does each task keep its ID?",
    ["Yes", "No, IDs become array positions", "Only if it is complete"],
    0,
    "An ID belongs to the task object and remains stable when the array is reversed.",
  ),
  question(
    "Starting at 2, three functional increments produce which result?",
    ["3", "5", "2"],
    1,
    "Each updater receives the result of the previous updater, so the values progress from 2 to 3 to 4 to 5.",
  ),
  question(
    "If you complete both tasks and show only unfinished tasks, what remains?",
    [
      "Both tasks",
      "An empty list and a remaining count of zero",
      "A loading error",
    ],
    1,
    "The visible list and remaining count are both calculated from the same task state.",
  ),
  question(
    "What will submitting only spaces do?",
    ["Save an invisible title", "Show a validation error", "Reload the page"],
    1,
    "Trimming spaces leaves an empty string. Validation rejects that value before saving.",
  ),
  question(
    "After switching learner identity, what happens to the draft?",
    ["It resets", "It duplicates", "It becomes the learner name"],
    0,
    "The changed key gives Draft a new identity with new local state.",
  ),
  question(
    "After clicking Focus task input, where will typing go?",
    ["Into the task input", "Into the button", "Nowhere until a render"],
    0,
    "The handler calls focus on the actual input DOM node.",
  ),
  question(
    "When a mounted subscription switches rooms, which event comes first?",
    [
      "Cleanup for the old room",
      "A message from the new room",
      "A second subscription with no cleanup",
    ],
    0,
    "React cleans up the previous Effect before running setup with the new room.",
  ),
  question(
    "Switch quickly from the slower Foundations request to Effects. Which results should remain?",
    ["Effects", "Foundations", "Whichever response finishes last"],
    0,
    "The latest selection wins. Cleanup cancels obsolete work and its result is ignored.",
  ),
  question(
    "Typing in the first draft should change the second draft too. True or false?",
    ["True", "False"],
    1,
    "These hook calls use independent state and different storage keys.",
  ),
  question(
    "After dispatching reset, what will the task array contain?",
    ["No tasks", "One reset task", "All tasks with new IDs"],
    0,
    "This reducer defines reset as returning an empty array.",
  ),
  question(
    "Choose Effects in consumer A. What does consumer B show?",
    ["Effects", "JSX", "A missing prop error"],
    0,
    "Both consumers read the same provider state, which the reducer updates.",
  ),
  question(
    "Opening task 1 should expose which parameter?",
    ['taskId: "1"', 'filter: "1"', "No parameter"],
    0,
    "The dynamic :taskId segment matches the path value 1.",
  ),
  question(
    "With stable props, can a memoized child skip an unrelated parent update?",
    ["Yes", "No, it must always render", "Only by deleting its state"],
    0,
    "memo can skip work when props compare equal. Measurements show behavior; skipping is not a correctness guarantee.",
  ),
  question(
    "While results catch up, should the input already show your latest text?",
    ["Yes", "No, it must wait for results", "Only after a request finishes"],
    0,
    "Input updates remain urgent while result updates can be deferred.",
  ),
  question(
    "If the lazy panel crashes during rendering, should the entire workspace disappear?",
    [
      "No, the boundary provides a local fallback",
      "Yes, always",
      "Only if the task list is empty",
    ],
    0,
    "The boundary surrounds the panel and contains its render failure.",
  ),
];
const docPaths = [
  "learn/your-first-component",
  "learn/passing-props-to-a-component",
  "learn/state-a-components-memory",
  "learn/rendering-lists",
  "learn/state-as-a-snapshot",
  "learn/updating-arrays-in-state",
  "reference/react-dom/components/input",
  "learn/sharing-state-between-components",
  "learn/manipulating-the-dom-with-refs",
  "learn/synchronizing-with-effects",
  "reference/react/useEffect",
  "learn/reusing-logic-with-custom-hooks",
  "learn/extracting-state-logic-into-a-reducer",
  "learn/scaling-up-with-reducer-and-context",
  null,
  "reference/react/memo",
  "reference/react/useTransition",
  "reference/react/Suspense",
];
lessons.forEach((entry, i) => {
  entry.prediction = predictions[i];
  entry.docs = docPaths[i]
    ? "https://18.react.dev/" + docPaths[i]
    : "https://reactrouter.com/start/declarative/routing";
  entry.hints = [
    "Trace the value from the component that owns it to the place where it changes. Compare that path with the code excerpt.",
    entry.practice.explanation,
  ];
});
